# Site settings
title: Maya A. Horton
email: mah241@cam.ac.uk
description: >
  Astronomer, author, illustrator and sustainability expert
baseurl: ""       
url: "https://mayaahorton.github.io"

# Build settings
destination: ./_site

theme: minima      # if all else fails
plugins: []

# Markdown processor
markdown: kramdown
